https:
  host: "0.0.0.0"
  port: "8082"
  
hotel:
  wsdl: "http://taj-hotel-mock-api.us-e2.cloudhub.io/BookingServiceService/BookingServicePort?wsdl"
  service: "BookingServiceService"
  port: "BookingServicePort"